package sample.pgssl.verticles;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import sample.pgssl.client.IPostgresClient;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class PgFromWorker  extends AbstractVerticle {
    public static Logger log = LoggerFactory.getLogger(PgFromWorker.class);
    public static final String ADDRESS = "pgssl.worker";
    @Override
    public void start() throws Exception {
        super.start();
        final IPostgresClient client = IPostgresClient.create(vertx, config(), false, true);
        VerticleHelper.createConsumer(vertx, ADDRESS, client, log);
    }
}
