package sample.pgssl.verticles;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import sample.pgssl.client.IPostgresClient;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class PgFromBusEventLoop extends AbstractVerticle {
    public static Logger log = LoggerFactory.getLogger(PgFromBusEventLoop.class);
    @Override
    public void start() throws Exception {
        super.start();
        IPostgresClient.initPostgresConsumer(vertx, config(), true);
    }
}
