/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.json.JsonObject;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.pgclient.PgConnectOptions;
import io.vertx.pgclient.SslMode;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.testcontainers.containers.PostgreSQLContainer;

import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.Assert.*;

@RunWith(VertxUnitRunner.class)
public class PgSslTest {
    @ClassRule
    public static PostgreSQLContainer<?> pg = new PostgreSQLContainer<>("postgres:14-ssl")
            .withDatabaseName("pgssl")
            .withUsername("pgssl")
            .withPassword("pgssl");
    static Logger log = LoggerFactory.getLogger(PgSslTest.class);
    final Vertx vertx = Vertx.vertx();

    @Before
    public void before(final TestContext context){
        final JsonObject postgresConfig = new JsonObject();
        postgresConfig.put("ssl-mode", SslMode.REQUIRE.name());
        postgresConfig.put("port", pg.getMappedPort(5432));
        postgresConfig.put("host", pg.getHost());
        postgresConfig.put("database", pg.getDatabaseName());
        postgresConfig.put("user", pg.getUsername());
        postgresConfig.put("password", pg.getPassword());
        final JsonObject config = new JsonObject().put("postgresConfig",postgresConfig);
        vertx.deployVerticle(new PgFromBus(), new DeploymentOptions().setConfig(config), context.asyncAssertSuccess());
        vertx.deployVerticle(new PgFromEventLoop(), new DeploymentOptions().setConfig(config), context.asyncAssertSuccess());
        vertx.deployVerticle(new PgFromWorker(), new DeploymentOptions().setConfig(config).setWorker(true), context.asyncAssertSuccess());
    }

    @Test
    public void shouldFailToInitFromWorker(final TestContext context) {
        final EventBus bus = vertx.eventBus();
        final JsonObject body = new JsonObject();
        log.info("Trying to query from worker");
        bus.request(PgFromWorker.ADDRESS, body, context.asyncAssertFailure(result -> {
            log.info("Test has failed as expected");
        }));
    }
    @Test
    public void shouldSucceedToInitFromEventLoop(final TestContext context) {
        final EventBus bus = vertx.eventBus();
        final JsonObject body = new JsonObject();
        log.info("Trying to query from event loop");
        bus.request(PgFromEventLoop.ADDRESS, body, context.asyncAssertSuccess(result -> {
            log.info("Test has succeed as expected");
        }));
    }

    @Test
    public void shouldFailRandomlyToInitFromWorkerUsingBus(final TestContext context) {
        final int max = 5;
        final EventBus bus = vertx.eventBus();
        final JsonObject body = new JsonObject();
        final Async async = context.async(max);
        log.info("Trying to query from bus");
        final AtomicInteger count = new AtomicInteger();
        for(int i = 0 ; i < max; i++){
            final int temp = i;
            bus.request(PgFromBus.ADDRESS, body,result -> {
                log.info(String.format("Test n° %s | result=%s | cause=%s", temp, result.succeeded(), result.cause()));
                if(result.succeeded()){
                    count.incrementAndGet();
                }
                async.countDown();
            });
        }
        async.handler(result -> {
            log.info(String.format("Count finish | count = %s | succeed=%s", async.count(), count.get()));
        });
    }
}
